baseURL = '/'
languageCode = 'en-us'
title = 'The SF Nexus'
theme = "gohugo-theme-ananke"
canonifyURLS=true
[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/About'
  weight = 1
[[menu.main]]
  name = 'Data'
  pageRef = '/Data'
  weight = 1
